name: web
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14.2
          enable-cache: "true"
          restore-cache: "true"
          activate-environment: "true"
          quiet: "true"

      - name: Create venv
        run: |
          uv venv .venv
          source .venv/bin/activate

      - name: Set up Python
        run: uv python install

      - run: uv sync
      - run: uv run mkdocs gh-deploy --force --quiet
